import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import Footer from "./components/Footer";

// Fonts

const roboto_font = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "300", "500", "700"],
});

export const metadata: Metadata = {
  title: "Hope Foundation",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main lang="en" data-theme="forest">
      <div className={`${roboto_font.variable} antialiased h-[90vh]`}>
        {children}
        <Footer />
      </div>
    </main>
  );
}
