import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";

// Fonts

const roboto_font = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "300", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main lang="en" data-theme="forest h-[90vh]">
      <div className={`${roboto_font.variable} antialiased`}>{children}</div>
    </main>
  );
}
